name: Friends locator workflow

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"
    types:
      - closed

jobs:

  deploy:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/friends-locator-backend:latest

            sudo docker-compose stop
            sudo docker-compose rm -f backend
            touch .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            sudo docker-compose up -d

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    steps:
      - name: Sending message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }}
            ${{ github.actor }} created commit:
                        Commit message: ${{ github.event.commits[0].message }}

                        Repository: ${{ github.repository }}

                        See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
